# Test 2024-05-05 at 21:30:14

name: Test
run-name: and

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Files - before
      run: |
        tree -h

    - name: Test silicon chips
      run: |
        java --enable-preview --source 22  Chip.j

    - name: Files - after
      run: |
        tree -h

    - uses: actions/upload-artifact@v4
      with:
        name: Chip
        path: .
