# Test 2024-06-11 at 03:31:15

name: Test
run-name: Silicon Chip

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Compile
      run: |
        mkdir -p com/AppaApps/Silicon/tests
        cp       *.java com/AppaApps/Silicon/
        cp tests/*.java com/AppaApps/Silicon/tests
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/Chip.java
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/RiscV.java
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/tests/Test1.java

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Files
      run:
        tree

    - name: Test Risc V
      run: |
        java -cp Classes com/AppaApps/Silicon/RiscV

    - name: Cpan
      run:  sudo cpan install -T Data::Dump Data::Table::Text GDS2 Digest::SHA1

    - name: Test silicon chips
      run: |
        java -cp Classes com/AppaApps/Silicon/Chip

    - name: Files
      run: |
        tree -h

    - uses: actions/upload-artifact@v4
      with:
        name: Chip
        path: .

    - run: |
        rm -f gds.zip
        zip gds gds/*
        ls -lah gds.zip
        git config user.name "aaa"
        git config user.email "aaa@aaa.com"
        git pull
        git add gds.zip
        git commit -m "GDS2 tape-out"
        git push
