# Test 2024-05-04 at 19:21:09

name: Test
run-name: #!/usr/bin/perl -I/home/phil/perl/cpan/SvgSimple/lib/ -I/home/phil/perl/cpan/SiliconChip/lib/ -I/home/phil/perl/cpan/SiliconChipLayout/lib/ -I/home/phil/perl/cpan/SiliconChipWiring/lib/ -I/home/phil/perl/cpan/Math-Intersection-Circle-Line/lib
#-------------------------------------------------------------------------------
# Implement a B-Tree as a silicon chip.
# Philip R Brenan at appaapps dot com, Appa Apps Ltd Inc., 2023
#-------------------------------------------------------------------------------
# Database on a chip: high speed low power database look ups save data center operators money on their electricity bills.
use v5.34;
package Silicon::Chip::Btree;
our $VERSION = 20240331;                                                        # Version
use warnings FATAL => qw(all

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Cpan
      run:  sudo cpan install -T Data::Dump Data::Table::Text GDS2 Digest::SHA1

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Files - before
      run: |
        tree -h

    - name: Test silicon chips
      run: |
        java Chip.java

    - name: Files - after
      run: |
        tree -h

    - uses: actions/upload-artifact@v4
      with:
        name: Chip
        path: .
