# Test 2024-07-20 at 04:51:58

name: Test
run-name: Silicon Chip

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [Chip, RiscV, Ban]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: 'JDK 22'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Position
      run: |
        mkdir -p com/AppaApps/Silicon/tests
        cp       *.java com/AppaApps/Silicon
        cp tests/*.java com/AppaApps/Silicon/tests

    - name: Files
      run:
        tree

    - name: Compile
      run: |
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/Chip.java com/AppaApps/Silicon/RiscV.java com/AppaApps/Silicon/Ban.java com/AppaApps/Silicon/tests/Test1.java

    - name: Test Risc V
      if: matrix.task == 'RiscV'
      run: |
        java -cp Classes com/AppaApps/Silicon/RiscV

    - name: Test Ban
      if: matrix.task == 'Ban'
      run: |
        java -cp Classes com/AppaApps/Silicon/Ban

    - name: Cpan
      if: matrix.task == 'Chip'
      run:  sudo cpan install -T Data::Dump Data::Table::Text GDS2 Digest::SHA1

    - name: Test silicon chips
      if: matrix.task == 'Chip'
      run: |
        java -cp Classes com/AppaApps/Silicon/Chip

    - name: Files
      if: matrix.task == 'Chip'
      run: |
        tree -h

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: matrix.task == 'Chip'
      with:
        name: Chip
        path: .

    - name: Upload GDS2
      if: matrix.task == 'ChipSuppress'
      run: |
        rm -f gds.zip
        zip gds gds/*
        ls -lah gds.zip
        git config user.name "aaa"
        git config user.email "aaa@aaa.com"
        git pull
        git add gds.zip
        git commit -m "GDS2 tape-out"
        git push
